### ISSUE TITLE
Double Upkeep

### ISSUE THREAD

**Issue by fiercefight** [GingerWalnut/SQ5.0Public#116]
I have noticed recently that upkeep has been collecting twice a day. I have a screenshot of my colony bank from yesterday 
![2018-01-11_22 00 51](https://user-images.githubusercontent.com/9440176/34902553-f031fcc8-f7eb-11e7-81e2-8102ba44fc47.png)
and now today 
![2018-01-12_22 53 33](https://user-images.githubusercontent.com/9440176/34902560-0acd15b8-f7ec-11e7-89eb-cb17732357f4.png) as you can see my balance has gone down 15k in the course of one day while my balance should have only gone down 7.5k

**Comment by JC3371** [comment]
I can atest to this

**Comment by martinjonsson01** [comment]
I believe upkeep wasn't collected the day before this happened, so that might be what is causing this.

**Comment by GingerWalnut** [comment]
It doesn't collect upkeep at a regular time interval, only when it has been 1 day or more since the last time it collected upkeep. Therefore, it is possible that you hit it at just the wrong times and it appears that it was collected twice in a day, but it was in fact not. Will close until another example of this occurs. Will work on getting this to occur at a regular time of day.
