### ISSUE TITLE
A complaint about colonies

### ISSUE THREAD

**Issue by MemeMaster77** [GingerWalnut/SQ5.0Public#96]
Me along with almost everyone I have spoken to about this has found it very frustrating, in colonies pvp is disabled, this means people can just run to their colony when being chased and be completely safe. It is made even worse now that many people are expanding into space, such as skydogs, who branched off with another colony in space. It makes the server a lot less fun not only in my opinion but also in most of the people I have spoke to.

**Comment by GingerWalnut** [comment]
If your not a member of a colony, you arn't protected by its protection. This prevents people from making a sister colony in space and being able to flee to it. Its either all or nothing

On the subject of pvp in colonies: It might be frustrating and less fun for you if you can't attack somone in a colony. However, its a whole lot less fun and a ton more frustrating for newer players who have just started as they will die and might lose everything they have. We might look into this system some more to allow more established groups to be attacked while newer players cannot.

**Comment by IggyW** [comment]
Idea: have "temp colonies" that each new player can have for only a week, free of charge, then it disappears automatically. 
However, since you cant run into any colony and be safe i think all colonies should continue to be pvp-free zones for their colony members.
I also think the taxes should be raised a LOT, make it 1000 per chunk per day at least. This ensures that colonies could be dissolved if its members aren't active enough. 
Maybe, after federations and territories are implemented, add a colony tax for every player in the colony (the more players in a colony, the more the colony has to pay the server in taxes)

**Comment by GingerWalnut** [comment]
This has been as fixed as it ever will be
