### ISSUE TITLE
Colonies/ship flying bug

### ISSUE THREAD

**Issue by Shocklor** [GingerWalnut/SQ5.0Public#97]
Seems i was not the only one to encounter this tonight, when flying your ship it will glitch and not allow you to move the ship inside a colony claim then afterwards will spam you this continuously until it stops

10/01/2018 
12:45am (EST) 

![image](https://user-images.githubusercontent.com/35117954/34757577-31126c94-f5a0-11e7-95c5-36600c6a1830.png)
Image attached via saltystare

**Comment by martinjonsson01** [comment]
Seems like it goes away after a while, but comes back after you relog. Also (appears like) it gets worse after relogging.

**Comment by SomethingSomethingAllison** [comment]
Its started doing new things after the restart, I now get messages saying I'm entering factions not even on the same planet and getting new messages involving entities and players. This bug is so bizarre.
![2018-01-10_11 53 56](https://user-images.githubusercontent.com/35288651/34787877-68ce3088-f5fe-11e7-8acc-e6acd47bd2bd.png)

**Comment by SomethingSomethingAllison** [comment]
I just found out that PVP is somehow enabled in my colony claim and mobs can also damage me, so I'm adding this to the reports

**Comment by GingerWalnut** [comment]
Fixed
